import { SIDEBAR_WIDTH_DEFAULT } from './constants.js';

export const state = {
  mode: 'view',
  currentFilePath: null,
  currentFolderPath: null,
  folderItems: [],
  content: '',
  isDirty: false,
  fileMissing: false,
  currentFileMtime: null,
  fileListFilter: '',
  tagFilter: [],
  renamingPath: null,
  tagPopoverPath: null,
  lastOpened: {},
  recents: [],
  findQuery: '',
  findIndex: 0,
  findMatches: [],
  settings: null,
  autoSaveTimer: null,
  autoSaveError: null,
  systemFonts: null,
  systemFontsPromise: null,
  splitSyncLock: false,
  previewStale: false,
  pendingFolderItems: null,
  fileListFocusIndex: -1,
  fileListAnimate: true,
  contextTargetPath: null,
  preferredSidebarWidth: SIDEBAR_WIDTH_DEFAULT,
  imageResolveCache: new Map(),
};

export const elements = {};

export function initElements() {
  const $ = (sel) => document.querySelector(sel);

  Object.assign(elements, {
    sidebar: $('#sidebar'),
    folderName: $('#folder-name'),
    fileList: $('#file-list'),
    fileListSearch: $('#file-list-search'),
    fileListEmpty: $('#file-list-empty'),
    fileListSort: $('#file-list-sort'),
    btnSortDirection: $('#btn-sort-direction'),
    tagFilter: $('#tag-filter'),
    tagFilterChips: $('#tag-filter-chips'),
    tagPopover: $('#tag-popover'),
    tagPopoverInput: $('#tag-popover-input'),
    tagPopoverSuggestions: $('#tag-popover-suggestions'),
    content: $('#content'),
    emptyState: $('#empty-state'),
    emptyRecents: $('#empty-recents'),
    emptyRecentFolders: $('#empty-recent-folders'),
    emptyRecentFoldersList: $('#empty-recent-folders-list'),
    emptyRecentFiles: $('#empty-recent-files'),
    emptyRecentFilesList: $('#empty-recent-files-list'),
    sidebarResizeHandle: $('#sidebar-resize-handle'),
    editorPane: $('#editor-pane'),
    previewPane: $('#preview-pane'),
    editor: $('#editor'),
    editorHighlights: $('#editor-highlights'),
    preview: $('#preview'),
    statusFile: $('#status-file'),
    statusMode: $('#status-mode'),
    statusStats: $('#status-stats'),
    btnSave: $('#btn-save'),
    btnClose: $('#btn-close'),
    btnSettings: $('#btn-settings'),
    btnToggleSidebar: $('#btn-toggle-sidebar'),
    btnRefreshFolder: $('#btn-refresh-folder'),
    btnNewFile: $('#btn-new-file'),
    btnNewFileTop: $('#btn-new-file-top'),
    modeBtns: document.querySelectorAll('.mode-btn'),
    findBar: $('#find-bar'),
    findInput: $('#find-input'),
    findCount: $('#find-count'),
    findPrev: $('#find-prev'),
    findNext: $('#find-next'),
    findClose: $('#find-close'),
    settingsOverlay: $('#settings-overlay'),
    settingsClose: $('#settings-close'),
  });
}
